-- 01 VSE O CDJIH
SELECT * FROM CDji;

-- 02 VSE ZVRSTI
SELECT DISTINCT ZVRST FROM CDji ORDER BY ZVRST DESC;

-- 03 DIJAKI IZ CELJA
SELECT * FROM DIJAKI WHERE KRAJ = 'Celje';

-- 04 ŽENSKI DIJAKI IZ CELJA
SELECT IME, PRIIMEK, TELEFON FROM DIJAKI
WHERE KRAJ = 'Celje' AND SPOL = 'Ž'
ORDER BY PRIIMEK;

-- 05 DIJAKI IZ ŽALCA ALI CELJA
SELECT IME, PRIIMEK, KRAJ, TELEFON FROM DIJAKI
WHERE KRAJ IN ('Celje', 'Žalec')
ORDER BY KRAJ DESC, PRIIMEK ASC;

-- 06 ŽENSKI DIJAKI
SELECT IME, PRIIMEK, KRAJ, TELEFON FROM DIJAKI
WHERE KRAJ IN ('Žalec', 'Celje') AND SPOL = 'Ž'
ORDER BY PRIIMEK;

-- 07 DIJAKI ROJENI 1990
SELECT IME, PRIIMEK, DATUM_R FROM DIJAKI
WHERE YEAR(DATUM_R) = 1990
ORDER BY DATUM_R DESC;

-- 08 DIJAKI NECELJANI ROJENI PO 1/1/1990
SELECT IME, PRIIMEK, DATUM_R FROM DIJAKI
WHERE DATUM_R > '1990-01-01' AND KRAJ != 'Celje';

-- 09 DIJAKI NA J
SELECT IME, PRIIMEK FROM DIJAKI
WHERE IME LIKE 'J%';

-- 10 DIJAKI, KI NA DRUGEM MESTU PRIIMKA NIMAJO A, E ALI O
SELECT * FROM DIJAKI
WHERE SUBSTRING(PRIIMEK, 2, 1) NOT IN ('a', 'e', 'o', 'A', 'E', 'O');

-- 10 ZALOŽBE S POP CDJI
SELECT DISTINCT ZALOZBA FROM CDji
WHERE ZVRST = 'pop';

-- 11 IZVAJALCI IN NASLOVI NEKLASIČNIH CDJEV IZPRED LETA 2000
SELECT IZVAJALEC, NASLOV, ZVRST FROM CDji
WHERE LETNICA < '2000' AND ZVRST != 'klasika'
ORDER BY ZVRST, IZVAJALEC;

-- 12 POP IN ROCK CDJI IZDANI MED LETOMA 1995 IN 2003
SELECT IZVAJALEC, NASLOV, LETNICA, ZALOZBA FROM CDji
WHERE LETNICA BETWEEN '1995' AND '2003' AND ZVRST IN ('pop', 'rock')
ORDER BY IZVAJALEC;

-- 13 POP IN ROCK CDJI IZDANI MED LETOMA 1990 IN 2000 KATERIH IZVAJALCI SE ZAČNEJO NA SAMOGLASNIK
SELECT * FROM CDji
WHERE LETNICA BETWEEN '1990' AND '2000'
  AND ZVRST != 'pop'
AND (IZVAJALEC LIKE 'A%' OR IZVAJALEC LIKE 'E%' OR IZVAJALEC LIKE 'I%' OR IZVAJALEC LIKE 'O%' OR IZVAJALEC LIKE 'U%')
ORDER BY DATUM_PRIDOBITVE ASC;

-- 14 ŠIFRE NASLOVI IN IZVAJALCI NEDVOJNIH CDJEV Z ZALOŽBO NA A ALI DRUGO ČRKO V NALOVU A
SELECT SIFRA, NASLOV, IZVAJALEC FROM CDji
WHERE (ZALOZBA LIKE '%a%' OR ZALOZBA LIKE '%A%' OR SUBSTRING(NASLOV, 2, 1) IN ('a', 'A'))
  AND ST_CDJEV = 1;

-- 15 ŠIFRE NASLOVI IN IZVAJALCI NEDVOJNIH CDJEV Z ZALOŽBO NA A DO 5 IN SOGLASNIKOM NA DRUGEM MESTU
SELECT SIFRA, NASLOV, IZVAJALEC FROM CDji
WHERE SUBSTRING(ZALOZBA, 1, 1) BETWEEN 'A' AND 'P'
  AND SUBSTRING(ZALOZBA, 2, 1) NOT IN ('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U')
  AND ST_CDJEV = 1;

-- 16 IZPOSOJE 1 3 5
SELECT * FROM IZPOSOJA
WHERE SIFRA_IZPOSOJE IN (1, 3, 5);

-- 17 IZPOSOJE KI NIMAJO ŠIFRE 1 3 5
SELECT * FROM IZPOSOJA
WHERE SIFRA_IZPOSOJE NOT IN (1, 3, 5)
ORDER BY DATUM_IZPOSOJE;

-- 18 DIJAKI S ŠIFRO MED 1 IN 4 ALI S ŠIFRO 6 8 9
SELECT IME, PRIIMEK FROM DIJAKI
WHERE (SIFRA BETWEEN 1 AND 4) OR SIFRA IN (6, 8, 9)
ORDER BY PRIIMEK DESC, IME DESC;