-- 11 VSI IZPOSOJENI CDJI_1
-- Z JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA;

-- Brez JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, DIJAKI D
WHERE I.SIFRA_DIJAKA = D.SIFRA;


-- 12 VSI IZPOSOJENI CDJI RAZVRŠČENI PO ŠIFRI CDJA IN DATUMU_1
-- Z JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA
ORDER BY I.SIFRA_CDJA, I.DATUM_IZPOSOJE;

-- Brez JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, DIJAKI D
WHERE I.SIFRA_DIJAKA = D.SIFRA
ORDER BY I.SIFRA_CDJA, I.DATUM_IZPOSOJE;


-- 13 VSI ŠE IZPOSOJENI CDJI_1
-- Z JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA
WHERE I.DATUM_VRNITVE IS NULL;

-- Brez JOIN
SELECT I.SIFRA_CDJA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, DIJAKI D
WHERE I.SIFRA_DIJAKA = D.SIFRA AND I.DATUM_VRNITVE IS NULL;


-- 14 CDJI IZPOSOJENI PO 15_1_2006_1
-- Z JOIN
SELECT DISTINCT C.NASLOV, C.IZVAJALEC
FROM CDJI C
         INNER JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
WHERE I.DATUM_IZPOSOJE > '2006-01-15';

-- Brez JOIN
SELECT DISTINCT C.NASLOV, C.IZVAJALEC
FROM CDJI C, IZPOSOJA I
WHERE C.SIFRA = I.SIFRA_CDJA AND I.DATUM_IZPOSOJE > '2006-01-15';


-- 15 ROCK ALI POP CDJI IZPOSOJENI PO 15_1_2006_1
-- Z JOIN
SELECT DISTINCT C.NASLOV, C.IZVAJALEC
FROM CDJI C
         INNER JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
WHERE (C.ZVRST = 'rock' OR C.ZVRST = 'pop') AND I.DATUM_IZPOSOJE > '2006-01-15';

-- Brez JOIN
SELECT DISTINCT C.NASLOV, C.IZVAJALEC
FROM CDJI C, IZPOSOJA I
WHERE C.SIFRA = I.SIFRA_CDJA AND (C.ZVRST = 'rock' OR C.ZVRST = 'pop') AND I.DATUM_IZPOSOJE > '2006-01-15';


-- 16 VRNJENI ROCK ALI POP CDJI IZPOSOJENI PO 15_1_2006_1
-- Z JOIN
SELECT C.NASLOV, C.IZVAJALEC, I.DATUM_IZPOSOJE, I.DATUM_VRNITVE
FROM CDJI C
         INNER JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
WHERE (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND I.DATUM_VRNITVE IS NOT NULL
ORDER BY I.DATUM_VRNITVE DESC;

-- Brez JOIN
SELECT C.NASLOV, C.IZVAJALEC, I.DATUM_IZPOSOJE, I.DATUM_VRNITVE
FROM CDJI C, IZPOSOJA I
WHERE C.SIFRA = I.SIFRA_CDJA
  AND (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND I.DATUM_VRNITVE IS NOT NULL
ORDER BY I.DATUM_VRNITVE DESC;


-- 17 VSI IZPOSOJENI CDJI_2
-- Z JOIN
SELECT C.NASLOV, C.SIFRA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA;

-- Brez JOIN
SELECT C.NASLOV, C.SIFRA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, CDJI C, DIJAKI D
WHERE I.SIFRA_CDJA = C.SIFRA AND I.SIFRA_DIJAKA = D.SIFRA;


-- 18 VSI IZPOSOJENI CDJI RAZVRŠČENI PO ŠIFRI CDJA IN DATUMU_2
-- Z JOIN
SELECT C.NASLOV, C.SIFRA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA
ORDER BY C.NASLOV, I.DATUM_IZPOSOJE;

-- Brez JOIN
SELECT C.NASLOV, C.SIFRA, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, CDJI C, DIJAKI D
WHERE I.SIFRA_CDJA = C.SIFRA AND I.SIFRA_DIJAKA = D.SIFRA
ORDER BY C.NASLOV, I.DATUM_IZPOSOJE;


-- 19 VSI ŠE IZPOSOJENI CDJI_2
-- Z JOIN
SELECT C.NASLOV, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         INNER JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA
WHERE I.DATUM_VRNITVE IS NULL;

-- Brez JOIN
SELECT C.NASLOV, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM IZPOSOJA I, CDJI C, DIJAKI D
WHERE I.SIFRA_CDJA = C.SIFRA AND I.SIFRA_DIJAKA = D.SIFRA AND I.DATUM_VRNITVE IS NULL;


-- 20 CDJI IZPOSOJENI PO 15_1_2006_2
-- Z JOIN
SELECT DISTINCT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE I.DATUM_IZPOSOJE > '2006-01-15';

-- Brez JOIN
SELECT DISTINCT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC
FROM DIJAKI D, IZPOSOJA I, CDJI C
WHERE D.SIFRA = I.SIFRA_DIJAKA AND I.SIFRA_CDJA = C.SIFRA AND I.DATUM_IZPOSOJE > '2006-01-15';


-- 21 ROCK ALI POP CDJI IZPOSOJENI PO 15_1_2006_2
-- Z JOIN
SELECT DISTINCT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND D.SPOL = 'M';

-- Brez JOIN
SELECT DISTINCT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC
FROM DIJAKI D, IZPOSOJA I, CDJI C
WHERE D.SIFRA = I.SIFRA_DIJAKA
  AND I.SIFRA_CDJA = C.SIFRA
  AND (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND D.SPOL = 'M';


-- 22 VRNJENI ROCK ALI POP CDJI IZPOSOJENI PO 15_1_2006_2
-- Z JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC, I.DATUM_IZPOSOJE, I.DATUM_VRNITVE
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND D.SPOL = 'M'
  AND I.DATUM_VRNITVE IS NOT NULL
ORDER BY I.DATUM_VRNITVE DESC;

-- Brez JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC, I.DATUM_IZPOSOJE, I.DATUM_VRNITVE
FROM DIJAKI D, IZPOSOJA I, CDJI C
WHERE D.SIFRA = I.SIFRA_DIJAKA
  AND I.SIFRA_CDJA = C.SIFRA
  AND (C.ZVRST = 'rock' OR C.ZVRST = 'pop')
  AND I.DATUM_IZPOSOJE > '2006-01-15'
  AND D.SPOL = 'M'
  AND I.DATUM_VRNITVE IS NOT NULL
ORDER BY I.DATUM_VRNITVE DESC;


-- 23 DIJAKI IZ KRAJEV S ČRKO A IN NJIHOVI IZPOSOJENI CDJE KI NISO ZVRSTI ROCK
-- Z JOIN
SELECT D.IME, D.PRIIMEK, D.KRAJ, C.*
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE D.KRAJ LIKE '%a%'
  AND C.ZVRST != 'rock'
  AND YEAR(I.DATUM_IZPOSOJE) = 2006;

-- Brez JOIN
SELECT D.IME, D.PRIIMEK, D.KRAJ, C.*
FROM DIJAKI D, IZPOSOJA I, CDJI C
WHERE D.SIFRA = I.SIFRA_DIJAKA
  AND I.SIFRA_CDJA = C.SIFRA
  AND D.KRAJ LIKE '%a%'
  AND C.ZVRST != 'rock'
  AND YEAR(I.DATUM_IZPOSOJE) = 2006;


-- 24 DIJAKI S KOMENTARJI IN SKLADBE
-- Z JOIN
SELECT D.IME, D.PRIIMEK, D.KOMENTAR, D.KRAJ, S.*
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN SKLADBE S ON I.SIFRA_CDJA = S.SIFRA_CDJA
WHERE D.KOMENTAR IS NOT NULL;

-- Brez JOIN
SELECT D.IME, D.PRIIMEK, D.KOMENTAR, D.KRAJ, S.*
FROM DIJAKI D, IZPOSOJA I, SKLADBE S
WHERE D.SIFRA = I.SIFRA_DIJAKA
  AND I.SIFRA_CDJA = S.SIFRA_CDJA
  AND D.KOMENTAR IS NOT NULL;


-- 25 ŠIFRE IN NASLOVI CDJEV IN PESMI ZA VSE NASLOVE PESMI MANJŠE OD NASLOVA NJIHOVEGA CDJA
-- Z JOIN
SELECT C.SIFRA, C.NASLOV, S.NASLOV AS NASLOV_PESMI
FROM CDJI C
         INNER JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE S.NASLOV < C.NASLOV;

-- Brez JOIN
SELECT C.SIFRA, C.NASLOV, S.NASLOV AS NASLOV_PESMI
FROM CDJI C, SKLADBE S
WHERE C.SIFRA = S.SIFRA_CDJA AND S.NASLOV < C.NASLOV;


-- 26 DIJAKI IN CDJI KI SI JIH TI DIJAKI NISO IZPOSODILI
-- Z JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV
FROM DIJAKI D
         CROSS JOIN CDJI C
WHERE NOT EXISTS (
    SELECT 1
    FROM IZPOSOJA I
    WHERE I.SIFRA_DIJAKA = D.SIFRA AND I.SIFRA_CDJA = C.SIFRA
);

-- Brez JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV
FROM DIJAKI D, CDJI C
WHERE NOT EXISTS (
    SELECT 1
    FROM IZPOSOJA I
    WHERE I.SIFRA_DIJAKA = D.SIFRA AND I.SIFRA_CDJA = C.SIFRA
);


-- 27 NASLOVI LETNICE IN ZVRSTI CDJEV IZDANE ISTEGA LETA IN Z ISTO ZVRSTJO KOT VSAJ ŠE EN CD
-- Z JOIN
SELECT DISTINCT C1.NASLOV, C1.LETNICA, C1.ZVRST
FROM CDJI C1
         INNER JOIN CDJI C2 ON C1.LETNICA = C2.LETNICA AND C1.ZVRST = C2.ZVRST AND C1.SIFRA != C2.SIFRA
ORDER BY C1.LETNICA, C1.ZVRST;

-- Brez JOIN
SELECT DISTINCT C1.NASLOV, C1.LETNICA, C1.ZVRST
FROM CDJI C1, CDJI C2
WHERE C1.LETNICA = C2.LETNICA
  AND C1.ZVRST = C2.ZVRST
  AND C1.SIFRA != C2.SIFRA
ORDER BY C1.LETNICA, C1.ZVRST;


-- 28 VSI CDJI IN SKLADBE NA NJIH ZA CDJE Z VPISANIMI SKLADBAMI
-- Z JOIN
SELECT C.NASLOV, S.*
FROM CDJI C
         INNER JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
ORDER BY C.NASLOV;

-- Brez JOIN
SELECT C.NASLOV, S.*
FROM CDJI C, SKLADBE S
WHERE C.SIFRA = S.SIFRA_CDJA
ORDER BY C.NASLOV;


-- 29 PODATKI O DIJAKIH, CDJIH IN SKLADBAH ZA CDJE IZPOSOJENE PO 31.12.2005 KATERIH IZVAJALCI SE NE ZAČNEJO NA SAMOGLASNIK IN NISO ZVRSTI POP ALI ROCK
-- Z JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC, S.NASLOV AS NASLOV_SKLADBE, I.DATUM_IZPOSOJE
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         INNER JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE I.DATUM_IZPOSOJE > '2005-12-31'
  AND C.IZVAJALEC NOT LIKE '[aeiouAEIOU]%'
  AND C.ZVRST != 'rock'
  AND C.ZVRST != 'pop';

-- Brez JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, C.IZVAJALEC, S.NASLOV AS NASLOV_SKLADBE, I.DATUM_IZPOSOJE
FROM DIJAKI D, IZPOSOJA I, CDJI C, SKLADBE S
WHERE D.SIFRA = I.SIFRA_DIJAKA
  AND I.SIFRA_CDJA = C.SIFRA
  AND C.SIFRA = S.SIFRA_CDJA
  AND I.DATUM_IZPOSOJE > '2005-12-31'
  AND C.IZVAJALEC NOT LIKE '[aeiouAEIOU]%'
  AND C.ZVRST != 'rock'
  AND C.ZVRST != 'pop';