-- 30 VSI CDJI IN SKLADBE NA NJIH
-- Z LEFT JOIN
SELECT C.NASLOV, S.*
FROM CDJI C
         LEFT JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
ORDER BY C.NASLOV;

-- Z RIGHT JOIN
SELECT C.NASLOV, S.*
FROM SKLADBE S
         RIGHT JOIN CDJI C ON S.SIFRA_CDJA = C.SIFRA
ORDER BY C.NASLOV;


-- 31 CDJI Z NEVPISANIMI SKLADBAMI
-- Z LEFT JOIN
SELECT C.*
FROM CDJI C
         LEFT JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE S.SIFRA_CDJA IS NULL
ORDER BY C.ZVRST, C.LETNICA;

-- Z RIGHT JOIN
SELECT C.*
FROM SKLADBE S
         RIGHT JOIN CDJI C ON S.SIFRA_CDJA = C.SIFRA
WHERE S.SIFRA_CDJA IS NULL
ORDER BY C.ZVRST, C.LETNICA;


-- 32 ŠE NEIZPOSOJENI CDJI ZVRSTI ROCK
-- Z LEFT JOIN
SELECT C.*
FROM CDJI C
         LEFT JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
WHERE I.SIFRA_IZPOSOJE IS NULL AND C.ZVRST = 'rock';

-- Z RIGHT JOIN
SELECT C.*
FROM IZPOSOJA I
         RIGHT JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE I.SIFRA_IZPOSOJE IS NULL AND C.ZVRST = 'rock';


-- 33 NASLOVI IZVAJALCI IN ZVRSTI NEIZPOSOJENIH CDJEV KI NISO ZVRSTI POP
-- Z LEFT JOIN
SELECT C.NASLOV, C.IZVAJALEC, C.ZVRST
FROM CDJI C
         LEFT JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
WHERE I.SIFRA_IZPOSOJE IS NULL AND C.ZVRST != 'pop';

-- Z RIGHT JOIN
SELECT C.NASLOV, C.IZVAJALEC, C.ZVRST
FROM IZPOSOJA I
         RIGHT JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
WHERE I.SIFRA_IZPOSOJE IS NULL AND C.ZVRST != 'pop';


-- 34 DIJAKI KI SI NISO NIKOLI IZPOSODILI CDJA_1
-- Z LEFT JOIN
SELECT D.IME, D.PRIIMEK, D.TELEFON
FROM DIJAKI D
         LEFT JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
WHERE I.SIFRA_IZPOSOJE IS NULL;

-- Z RIGHT JOIN
SELECT D.IME, D.PRIIMEK, D.TELEFON
FROM IZPOSOJA I
         RIGHT JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA
WHERE I.SIFRA_IZPOSOJE IS NULL;


-- 35 NASLOVI DATUMI IZPOSOJE TER IMENA IN PRIIMKI ZA VSE CDJE
-- Z LEFT JOIN
SELECT C.NASLOV, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM CDJI C
         LEFT JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
         LEFT JOIN DIJAKI D ON I.SIFRA_DIJAKA = D.SIFRA;

-- Z RIGHT JOIN
SELECT C.NASLOV, I.DATUM_IZPOSOJE, D.IME, D.PRIIMEK
FROM DIJAKI D
         RIGHT JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         RIGHT JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA;


-- 36 VSI NEIZPOSOJENI CDJI IZDANI MED 1999 IN 2003 KI NISO ZVRSTI POP ALI ROCK IN IMAJO VPISANE SKLADBE IN NJIHOVE SKLADBE
-- Z LEFT JOIN
SELECT C.NASLOV, C.ZVRST, S.*
FROM CDJI C
         LEFT JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
         INNER JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE I.SIFRA_IZPOSOJE IS NULL
  AND C.LETNICA BETWEEN 1999 AND 2003
  AND C.ZVRST != 'pop'
  AND C.ZVRST != 'rock';

-- Z RIGHT JOIN
SELECT C.NASLOV, C.ZVRST, S.*
FROM IZPOSOJA I
         RIGHT JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         INNER JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE I.SIFRA_IZPOSOJE IS NULL
  AND C.LETNICA BETWEEN 1999 AND 2003
  AND C.ZVRST != 'pop'
  AND C.ZVRST != 'rock';


-- 37 VSI NEIZPOSOJENI CDJI IZDANI MED 1999 IN 2003 KI NISO ZVRSTI POP ALI ROCK IN NJIHOVE SKLADBE
-- Z LEFT JOIN
SELECT C.NASLOV, C.ZVRST, S.*
FROM CDJI C
         LEFT JOIN IZPOSOJA I ON C.SIFRA = I.SIFRA_CDJA
         LEFT JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE I.SIFRA_IZPOSOJE IS NULL
  AND C.LETNICA BETWEEN 1999 AND 2003
  AND C.ZVRST != 'pop'
  AND C.ZVRST != 'rock';

-- Z RIGHT JOIN
SELECT C.NASLOV, C.ZVRST, S.*
FROM SKLADBE S
         RIGHT JOIN (
    SELECT C.*
    FROM IZPOSOJA I
             RIGHT JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
    WHERE I.SIFRA_IZPOSOJE IS NULL
      AND C.LETNICA BETWEEN 1999 AND 2003
      AND C.ZVRST != 'pop'
      AND C.ZVRST != 'rock'
) C ON S.SIFRA_CDJA = C.SIFRA;


-- 38 DIJAKI IN SKLADBE CDJEV IZPOSOJENIH 2006
-- Z LEFT JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, S.NASLOV AS NASLOV_SKLADBE, S.DOLZINA
FROM DIJAKI D
         INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
         INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
         LEFT JOIN SKLADBE S ON C.SIFRA = S.SIFRA_CDJA
WHERE YEAR(I.DATUM_IZPOSOJE) = 2006;

-- Z RIGHT JOIN
SELECT D.IME, D.PRIIMEK, C.NASLOV, S.NASLOV AS NASLOV_SKLADBE, S.DOLZINA
FROM SKLADBE S
         RIGHT JOIN (
    SELECT D.IME, D.PRIIMEK, C.NASLOV, C.SIFRA
    FROM DIJAKI D
             INNER JOIN IZPOSOJA I ON D.SIFRA = I.SIFRA_DIJAKA
             INNER JOIN CDJI C ON I.SIFRA_CDJA = C.SIFRA
    WHERE YEAR(I.DATUM_IZPOSOJE) = 2006
) AS T ON S.SIFRA_CDJA = T.SIFRA;
